### ISSUE TITLE
textAlign not working on iOS

### ISSUE THREAD

**Issue by sajjadrad** [jsdf/react-native-htmlview#91] opened 2017-04-12 12:13 UTC

**Comment by flavordaaave** [comment] 2017-06-17 18:25
I'm trying to set `textAlign: center` on an `h1`. Setting a `backgroundColor` to the `h1` tag shows that the problem is that the view is not taking the full width. So I tried setting `width: Dimensions.get('window').width` but the `h1` is still NOT taking the full width and not centered.

**Comment by flavordaaave** [comment] 2017-06-17 20:39
#58 has a working solution

**Comment by richchurcher** [comment] 2017-07-03 23:12
Closing in favour of #58 .

**Closed by richchurcher** 2017-07-03 23:12 UTC
